// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kubpsfiahmxqubspefdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1YnBzZmlhaG14cXVic3BlZmRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMjU4OTcsImV4cCI6MjA2MTYwMTg5N30.c_kv5qdDM6wRkwv0cFgfsd4OMMTIzGuB2SOL9O6Ys0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);